Import QVariant in examples that require it
Those examples that make use of `QVariant` currently fail when used in
the Python Console with:

    NameError: name 'QVariant' is not defined